import requests
import json
import urllib.parse
import os
from dotenv import load_dotenv
import http.client

# Load environment variables from .env file
load_dotenv()

# Function to check if a contact already exists in GoDial
def check_contact_exists(phone):
    API_TOKEN = os.getenv("GODIAL_API_TOKEN")
    list_id = os.getenv("GODIAL_LIST_ID")
    
    conn = http.client.HTTPSConnection("enterprise.godial.cc")
    headers = {
        "Accept": "application/json, multipart/form-data, application/x-www-form-urlencoded"
    }

    # Build the request URL
    url = f"/meta/api/externals/contact/list/{list_id}?access_token={API_TOKEN}"
    conn.request("GET", url, headers=headers)
    
    try:
        res = conn.getresponse()
        data = res.read().decode("utf-8")
        contacts = json.loads(data)
        
        # Iterate through the list of contacts to check if the phone number exists
        for contact in contacts:
            if contact.get('phone') == phone:
                return True  # Contact exists
        return False  # Contact does not exist
    except Exception as e:
        print(f"An error occurred while checking if contact exists: {e}")
        return False  # Assume contact does not exist if an error occurs

# Function to add a new contact to GoDial
def add_contact_to_godial(property_data):
    API_TOKEN = os.getenv("GODIAL_API_TOKEN")
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "application/json, multipart/form-data, application/x-www-form-urlencoded"
    }

    godial_data = {
        "name": property_data['name'],
        "email": property_data['email'],
        "phone": property_data['mobile_number'],
        "companyName": property_data['cname'],
        "note": "Generated by system",
        "listId": os.getenv("GODIAL_LIST_ID"),
        "accountsId": os.getenv("GODIAL_ACCOUNTS_ID"),
        "customFields": json.dumps([
            {"name": "SEATS", "value": str(property_data['seats'])},
            {"name": "CITY", "value": property_data['city']},
            {"name": "MICROMARKET", "value": property_data['micromarket']},
            {"name": "OPTION_SHARED", "value": property_data['property_names']}
        ])
    }

    payload = urllib.parse.urlencode(godial_data)
    godial_url = f"https://enterprise.godial.cc/meta/api/externals/contact/add?access_token={API_TOKEN}"
    
    try:
        response = requests.post(godial_url, headers=headers, data=payload)
        if response.status_code == 200 or response.status_code == 201:
            print(f"Contact '{godial_data['name']}' added successfully to GoDial.")
        else:
            print(f"Failed to add contact to GoDial: {response.status_code} - {response.text}")
    except Exception as e:
        print(f"An error occurred while adding contact to GoDial: {e}")

# Function to handle the logic of checking if the contact exists and adding if it doesn't
def send_data_to_godial(property_data):
    phone = property_data['mobile_number']

    if check_contact_exists(phone):
        print(f"Contact with phone number {phone} already exists. Skipping addition.")
    else:
        print("Contact does not exist. Adding new contact...")
        add_contact_to_godial(property_data)
